insert into country (country_name, country_code) VALUES ('Djibouti', 'DJ');
insert into country (country_name, country_code) VALUES ('Montserrat', 'MS');
insert into country (country_name, country_code) VALUES ('Philippines', 'PH');
insert into country (country_name, country_code) VALUES ('Dominican Republic', 'DO');
insert into country (country_name, country_code) VALUES ('Israel', 'IL');
insert into country (country_name, country_code) VALUES ('Slovakia', 'SK');
insert into country (country_name, country_code) VALUES ('Spain', 'ES');
insert into country (country_name, country_code) VALUES ('Togo', 'TG');
insert into country (country_name, country_code) VALUES ('US Minor Outlying Islands', 'UM');
insert into country (country_name, country_code) VALUES ('British Virgin Islands', 'VG');
insert into country (country_name, country_code) VALUES ('Luxembourg', 'LU');
insert into country (country_name, country_code) VALUES ('San Marino', 'SM');
insert into country (country_name, country_code) VALUES ('Swaziland', 'SZ');
insert into country (country_name, country_code) VALUES ('Tokelau', 'TK');
insert into country (country_name, country_code) VALUES ('Virgin Islands, US', 'VI');
insert into country (country_name, country_code) VALUES ('Ghana', 'GH');
insert into country (country_name, country_code) VALUES ('Kyrgyzstan', 'KG');
insert into country (country_name, country_code) VALUES ('Saint Helena', 'SH');
insert into country (country_name, country_code) VALUES ('Azerbaijan', 'AZ');
insert into country (country_name, country_code) VALUES ('Guatemala', 'GT');
insert into country (country_name, country_code) VALUES ('Korea (South)', 'KR');
insert into country (country_name, country_code) VALUES ('Somalia', 'SO');
insert into country (country_name, country_code) VALUES ('Czech Republic', 'CZ');
insert into country (country_name, country_code) VALUES ('French Southern Territories', 'TF');
insert into country (country_name, country_code) VALUES ('Panama', 'PA');
insert into country (country_name, country_code) VALUES ('Sao Tome and Principe', 'ST');
insert into country (country_name, country_code) VALUES ('Antarctica', 'AQ');
insert into country (country_name, country_code) VALUES ('Lebanon', 'LB');
insert into country (country_name, country_code) VALUES ('Sierra Leone', 'SL');
insert into country (country_name, country_code) VALUES ('Thailand', 'TH');
insert into country (country_name, country_code) VALUES ('Albania', 'AL');
insert into country (country_name, country_code) VALUES ('Jordan', 'JO');
insert into country (country_name, country_code) VALUES ('Romania', 'RO');
insert into country (country_name, country_code) VALUES ('Belgium', 'BE');
insert into country (country_name, country_code) VALUES ('Palau', 'PW');
insert into country (country_name, country_code) VALUES ('China', 'CN');
insert into country (country_name, country_code) VALUES ('Guinea', 'GN');
insert into country (country_name, country_code) VALUES ('Pakistan', 'PK');
insert into country (country_name, country_code) VALUES ('Aruba', 'AW');
insert into country (country_name, country_code) VALUES ('Bhutan', 'BT');
insert into country (country_name, country_code) VALUES ('Burundi', 'BI');
insert into country (country_name, country_code) VALUES ('Saint-Barthélemy', 'BL');
insert into country (country_name, country_code) VALUES ('Republic of Kosovo', 'XK');
insert into country (country_name, country_code) VALUES ('United States of America', 'US');
insert into country (country_name, country_code) VALUES ('Costa Rica', 'CR');
insert into country (country_name, country_code) VALUES ('Equatorial Guinea', 'GQ');
insert into country (country_name, country_code) VALUES ('Heard and Mcdonald Islands', 'HM');
insert into country (country_name, country_code) VALUES ('Andorra', 'AD');
insert into country (country_name, country_code) VALUES ('Peru', 'PE');
insert into country (country_name, country_code) VALUES ('Martinique', 'MQ');
insert into country (country_name, country_code) VALUES ('Nicaragua', 'NI');
insert into country (country_name, country_code) VALUES ('Poland', 'PL');
insert into country (country_name, country_code) VALUES ('Zambia', 'ZM');
insert into country (country_name, country_code) VALUES ('Austria', 'AT');
insert into country (country_name, country_code) VALUES ('Christmas Island', 'CX');
insert into country (country_name, country_code) VALUES ('Guyana', 'GY');
insert into country (country_name, country_code) VALUES ('Madagascar', 'MG');
insert into country (country_name, country_code) VALUES ('El Salvador', 'SV');
insert into country (country_name, country_code) VALUES ('American Samoa', 'AS');
insert into country (country_name, country_code) VALUES ('Bangladesh', 'BD');
insert into country (country_name, country_code) VALUES ('Venezuela (Bolivarian Republic)', 'VE');
insert into country (country_name, country_code) VALUES ('Jamaica', 'JM');
insert into country (country_name, country_code) VALUES ('Papua New Guinea', 'PG');
insert into country (country_name, country_code) VALUES ('Slovenia', 'SI');
insert into country (country_name, country_code) VALUES ('Afghanistan', 'AF');
insert into country (country_name, country_code) VALUES ('Greece', 'GR');
insert into country (country_name, country_code) VALUES ('Hong Kong, SAR China', 'HK');
insert into country (country_name, country_code) VALUES ('Finland', 'FI');
insert into country (country_name, country_code) VALUES ('Gabon', 'GA');
insert into country (country_name, country_code) VALUES ('Zimbabwe', 'ZW');
insert into country (country_name, country_code) VALUES ('British Indian Ocean Territory', 'IO');
insert into country (country_name, country_code) VALUES ('Cayman Islands', 'KY');
insert into country (country_name, country_code) VALUES ('Estonia', 'EE');
insert into country (country_name, country_code) VALUES ('Sudan', 'SD');
insert into country (country_name, country_code) VALUES ('Iceland', 'IS');
insert into country (country_name, country_code) VALUES ('Korea (North)', 'KP');
insert into country (country_name, country_code) VALUES ('Liechtenstein', 'LI');
insert into country (country_name, country_code) VALUES ('New Zealand', 'NZ');
insert into country (country_name, country_code) VALUES ('Latvia', 'LV');
insert into country (country_name, country_code) VALUES ('Cocos (Keeling) Islands', 'CC');
insert into country (country_name, country_code) VALUES ('Ethiopia', 'ET');
insert into country (country_name, country_code) VALUES ('French Guiana', 'GF');
insert into country (country_name, country_code) VALUES ('Hungary', 'HU');
insert into country (country_name, country_code) VALUES ('Eritrea', 'ER');
insert into country (country_name, country_code) VALUES ('Guam', 'GU');
insert into country (country_name, country_code) VALUES ('Ukraine', 'UA');
insert into country (country_name, country_code) VALUES ('Egypt', 'EG');
insert into country (country_name, country_code) VALUES ('Uganda', 'UG');
insert into country (country_name, country_code) VALUES ('South Sudan', 'SS');
insert into country (country_name, country_code) VALUES ('Malawi', 'MW');
insert into country (country_name, country_code) VALUES ('Mayotte', 'YT');
insert into country (country_name, country_code) VALUES ('Micronesia, Federated States of', 'FM');
insert into country (country_name, country_code) VALUES ('Norfolk Island', 'NF');
insert into country (country_name, country_code) VALUES ('Côte d''Ivoire', 'CI');
insert into country (country_name, country_code) VALUES ('Jersey', 'JE');
insert into country (country_name, country_code) VALUES ('Maldives', 'MV');
insert into country (country_name, country_code) VALUES ('Western Sahara', 'EH');
insert into country (country_name, country_code) VALUES ('Australia', 'AU');
insert into country (country_name, country_code) VALUES ('Brunei Darussalam', 'BN');
insert into country (country_name, country_code) VALUES ('Cuba', 'CU');
insert into country (country_name, country_code) VALUES ('Saudi Arabia', 'SA');
insert into country (country_name, country_code) VALUES ('South Africa', 'ZA');
insert into country (country_name, country_code) VALUES ('Congo (Kinshasa)', 'CD');
insert into country (country_name, country_code) VALUES ('Guinea-Bissau', 'GW');
insert into country (country_name, country_code) VALUES ('Malaysia', 'MY');
insert into country (country_name, country_code) VALUES ('Mauritania', 'MR');
insert into country (country_name, country_code) VALUES ('Italy', 'IT');
insert into country (country_name, country_code) VALUES ('Libya', 'LY');
insert into country (country_name, country_code) VALUES ('New Caledonia', 'NC');
insert into country (country_name, country_code) VALUES ('Senegal', 'SN');
insert into country (country_name, country_code) VALUES ('Benin', 'BJ');
insert into country (country_name, country_code) VALUES ('Faroe Islands', 'FO');
insert into country (country_name, country_code) VALUES ('Honduras', 'HN');
insert into country (country_name, country_code) VALUES ('Uzbekistan', 'UZ');
insert into country (country_name, country_code) VALUES ('Pitcairn', 'PN');
insert into country (country_name, country_code) VALUES ('Tuvalu', 'TV');
insert into country (country_name, country_code) VALUES ('Argentina', 'AR');
insert into country (country_name, country_code) VALUES ('Bulgaria', 'BG');
insert into country (country_name, country_code) VALUES ('Fiji', 'FJ');
insert into country (country_name, country_code) VALUES ('Oman', 'OM');
insert into country (country_name, country_code) VALUES ('Taiwan, Republic of China', 'TW');
insert into country (country_name, country_code) VALUES ('Belarus', 'BY');
insert into country (country_name, country_code) VALUES ('Canada', 'CA');
insert into country (country_name, country_code) VALUES ('Denmark', 'DK');
insert into country (country_name, country_code) VALUES ('Isle of Man', 'IM');
insert into country (country_name, country_code) VALUES ('Mozambique', 'MZ');
insert into country (country_name, country_code) VALUES ('Tajikistan', 'TJ');
insert into country (country_name, country_code) VALUES ('Nauru', 'NR');
insert into country (country_name, country_code) VALUES ('Portugal', 'PT');
insert into country (country_name, country_code) VALUES ('Cambodia', 'KH');
insert into country (country_name, country_code) VALUES ('Germany', 'DE');
insert into country (country_name, country_code) VALUES ('Algeria', 'DZ');
insert into country (country_name, country_code) VALUES ('Kenya', 'KE');
insert into country (country_name, country_code) VALUES ('France', 'FR');
insert into country (country_name, country_code) VALUES ('Tunisia', 'TN');
insert into country (country_name, country_code) VALUES ('Uruguay', 'UY');
insert into country (country_name, country_code) VALUES ('Comoros', 'KM');
insert into country (country_name, country_code) VALUES ('Nepal', 'NP');
insert into country (country_name, country_code) VALUES ('Qatar', 'QA');
insert into country (country_name, country_code) VALUES ('Saint Kitts and Nevis', 'KN');
insert into country (country_name, country_code) VALUES ('Nigeria', 'NG');
insert into country (country_name, country_code) VALUES ('Paraguay', 'PY');
insert into country (country_name, country_code) VALUES ('Angola', 'AO');
insert into country (country_name, country_code) VALUES ('Bermuda', 'BM');
insert into country (country_name, country_code) VALUES ('Lao PDR', 'LA');
insert into country (country_name, country_code) VALUES ('Timor-Leste', 'TL');
insert into country (country_name, country_code) VALUES ('Tonga', 'TO');
insert into country (country_name, country_code) VALUES ('Viet Nam', 'VN');
insert into country (country_name, country_code) VALUES ('Gambia', 'GM');
insert into country (country_name, country_code) VALUES ('Liberia', 'LR');
insert into country (country_name, country_code) VALUES ('Syrian Arab Republic (Syria)', 'SY');
insert into country (country_name, country_code) VALUES ('Macao, SAR China', 'MO');
insert into country (country_name, country_code) VALUES ('Malta', 'MT');
insert into country (country_name, country_code) VALUES ('Monaco', 'MC');
insert into country (country_name, country_code) VALUES ('Northern Mariana Islands', 'MP');
insert into country (country_name, country_code) VALUES ('Anguilla', 'AI');
insert into country (country_name, country_code) VALUES ('Cape Verde', 'CV');
insert into country (country_name, country_code) VALUES ('Lesotho', 'LS');
insert into country (country_name, country_code) VALUES ('Puerto Rico', 'PR');
insert into country (country_name, country_code) VALUES ('Trinidad and Tobago', 'TT');
insert into country (country_name, country_code) VALUES ('Gibraltar', 'GI');
insert into country (country_name, country_code) VALUES ('Iraq', 'IQ');
insert into country (country_name, country_code) VALUES ('Myanmar', 'MM');
insert into country (country_name, country_code) VALUES ('South Georgia and the South Sandwich Islands', 'GS');
insert into country (country_name, country_code) VALUES ('Switzerland', 'CH');
insert into country (country_name, country_code) VALUES ('Turks and Caicos Islands', 'TC');
insert into country (country_name, country_code) VALUES ('Turkmenistan', 'TM');
insert into country (country_name, country_code) VALUES ('Bahamas', 'BS');
insert into country (country_name, country_code) VALUES ('Ireland', 'IE');
insert into country (country_name, country_code) VALUES ('Netherlands Antilles', 'AN');
insert into country (country_name, country_code) VALUES ('Singapore', 'SG');
insert into country (country_name, country_code) VALUES ('Tanzania, United Republic of', 'TZ');
insert into country (country_name, country_code) VALUES ('Niue', 'NU');
insert into country (country_name, country_code) VALUES ('Solomon Islands', 'SB');
insert into country (country_name, country_code) VALUES ('Greenland', 'GL');
insert into country (country_name, country_code) VALUES ('Holy See (Vatican City State)', 'VA');
insert into country (country_name, country_code) VALUES ('Kiribati', 'KI');
insert into country (country_name, country_code) VALUES ('Lithuania', 'LT');
insert into country (country_name, country_code) VALUES ('Armenia', 'AM');
insert into country (country_name, country_code) VALUES ('Palestinian Territory', 'PS');
insert into country (country_name, country_code) VALUES ('Sweden', 'SE');
insert into country (country_name, country_code) VALUES ('Wallis and Futuna Islands', 'WF');
insert into country (country_name, country_code) VALUES ('Brazil', 'BR');
insert into country (country_name, country_code) VALUES ('Chile', 'CL');
insert into country (country_name, country_code) VALUES ('United Arab Emirates', 'AE');
insert into country (country_name, country_code) VALUES ('Serbia', 'RS');
insert into country (country_name, country_code) VALUES ('Ecuador', 'EC');
insert into country (country_name, country_code) VALUES ('Iran, Islamic Republic of', 'IR');
insert into country (country_name, country_code) VALUES ('Namibia', 'NA');
insert into country (country_name, country_code) VALUES ('Norway', 'NO');
insert into country (country_name, country_code) VALUES ('Chad', 'TD');
insert into country (country_name, country_code) VALUES ('Niger', 'NE');
insert into country (country_name, country_code) VALUES ('United Kingdom', 'GB');
insert into country (country_name, country_code) VALUES ('Dominica', 'DM');
insert into country (country_name, country_code) VALUES ('Falkland Islands (Malvinas)', 'FK');
insert into country (country_name, country_code) VALUES ('Saint Lucia', 'LC');
insert into country (country_name, country_code) VALUES ('ALA Aland Islands', 'AX');
insert into country (country_name, country_code) VALUES ('Burkina Faso', 'BF');
insert into country (country_name, country_code) VALUES ('Turkey', 'TR');
insert into country (country_name, country_code) VALUES ('Central African Republic', 'CF');
insert into country (country_name, country_code) VALUES ('Cyprus', 'CY');
insert into country (country_name, country_code) VALUES ('Guernsey', 'GG');
insert into country (country_name, country_code) VALUES ('Haiti', 'HT');
insert into country (country_name, country_code) VALUES ('Antigua and Barbuda', 'AG');
insert into country (country_name, country_code) VALUES ('Macedonia, Republic of', 'MK');
insert into country (country_name, country_code) VALUES ('Bolivia', 'BO');
insert into country (country_name, country_code) VALUES ('French Polynesia', 'PF');
insert into country (country_name, country_code) VALUES ('Russian Federation', 'RU');
insert into country (country_name, country_code) VALUES ('Mauritius', 'MU');
insert into country (country_name, country_code) VALUES ('Japan', 'JP');
insert into country (country_name, country_code) VALUES ('Vanuatu', 'VU');
insert into country (country_name, country_code) VALUES ('Barbados', 'BB');
insert into country (country_name, country_code) VALUES ('Cook Islands', 'CK');
insert into country (country_name, country_code) VALUES ('Indonesia', 'ID');
insert into country (country_name, country_code) VALUES ('Bosnia and Herzegovina', 'BA');
insert into country (country_name, country_code) VALUES ('Grenada', 'GD');
insert into country (country_name, country_code) VALUES ('Mongolia', 'MN');
insert into country (country_name, country_code) VALUES ('Netherlands', 'NL');
insert into country (country_name, country_code) VALUES ('Congo (Brazzaville)', 'CG');
insert into country (country_name, country_code) VALUES ('Guadeloupe', 'GP');
insert into country (country_name, country_code) VALUES ('India', 'IN');
insert into country (country_name, country_code) VALUES ('Saint Pierre and Miquelon', 'PM');
insert into country (country_name, country_code) VALUES ('Croatia', 'HR');
insert into country (country_name, country_code) VALUES ('Marshall Islands', 'MH');
insert into country (country_name, country_code) VALUES ('Seychelles', 'SC');
insert into country (country_name, country_code) VALUES ('Sri Lanka', 'LK');
insert into country (country_name, country_code) VALUES ('Suriname', 'SR');
insert into country (country_name, country_code) VALUES ('Botswana', 'BW');
insert into country (country_name, country_code) VALUES ('Mali', 'ML');
insert into country (country_name, country_code) VALUES ('Mexico', 'MX');
insert into country (country_name, country_code) VALUES ('Rwanda', 'RW');
insert into country (country_name, country_code) VALUES ('Cameroon', 'CM');
insert into country (country_name, country_code) VALUES ('Kuwait', 'KW');
insert into country (country_name, country_code) VALUES ('Saint Vincent and Grenadines', 'VC');
insert into country (country_name, country_code) VALUES ('Samoa', 'WS');
insert into country (country_name, country_code) VALUES ('Saint-Martin (French part)', 'MF');
insert into country (country_name, country_code) VALUES ('Bouvet Island', 'BV');
insert into country (country_name, country_code) VALUES ('Georgia', 'GE');
insert into country (country_name, country_code) VALUES ('Morocco', 'MA');
insert into country (country_name, country_code) VALUES ('Svalbard and Jan Mayen Islands', 'SJ');
insert into country (country_name, country_code) VALUES ('Bahrain', 'BH');
insert into country (country_name, country_code) VALUES ('Belize', 'BZ');
insert into country (country_name, country_code) VALUES ('Montenegro', 'ME');
insert into country (country_name, country_code) VALUES ('Colombia', 'CO');
insert into country (country_name, country_code) VALUES ('Moldova', 'MD');
insert into country (country_name, country_code) VALUES ('Kazakhstan', 'KZ');
insert into country (country_name, country_code) VALUES ('Réunion', 'RE');
insert into country (country_name, country_code) VALUES ('Yemen', 'YE');

