
insert into country(country_name, country_code, country_slug) values ('Cameroon', 'CM', 'cameroon');
insert into country(country_name, country_code, country_slug) values ('Haiti', 'HT', 'haiti');
insert into country(country_name, country_code, country_slug) values ('Rwanda', 'RW', 'rwanda');
insert into country(country_name, country_code, country_slug) values ('Zambia', 'ZM', 'zambia');
insert into country(country_name, country_code, country_slug) values ('Trinidad and Tobago', 'TT', 'trinidad-and-tobago');
insert into country(country_name, country_code, country_slug) values ('Bolivia', 'BO', 'bolivia');
insert into country(country_name, country_code, country_slug) values ('Montserrat', 'MS', 'montserrat');
insert into country(country_name, country_code, country_slug) values ('Réunion', 'RE', 'réunion');
insert into country(country_name, country_code, country_slug) values ('Slovenia', 'SI', 'slovenia');
insert into country(country_name, country_code, country_slug) values ('China', 'CN', 'china');
insert into country(country_name, country_code, country_slug) values ('Micronesia, Federated States of', 'FM', 'micronesia');
insert into country(country_name, country_code, country_slug) values ('Comoros', 'KM', 'comoros');
insert into country(country_name, country_code, country_slug) values ('Kenya', 'KE', 'kenya');
insert into country(country_name, country_code, country_slug) values ('Japan', 'JP', 'japan');
insert into country(country_name, country_code, country_slug) values ('Morocco', 'MA', 'morocco');
insert into country(country_name, country_code, country_slug) values ('American Samoa', 'AS', 'american-samoa');
insert into country(country_name, country_code, country_slug) values ('France', 'FR', 'france');
insert into country(country_name, country_code, country_slug) values ('Georgia', 'GE', 'georgia');
insert into country(country_name, country_code, country_slug) values ('Bangladesh', 'BD', 'bangladesh');
insert into country(country_name, country_code, country_slug) values ('Brunei Darussalam', 'BN', 'brunei');
insert into country(country_name, country_code, country_slug) values ('Guam', 'GU', 'guam');
insert into country(country_name, country_code, country_slug) values ('Germany', 'DE', 'germany');
insert into country(country_name, country_code, country_slug) values ('Jordan', 'JO', 'jordan');
insert into country(country_name, country_code, country_slug) values ('Mayotte', 'YT', 'mayotte');
insert into country(country_name, country_code, country_slug) values ('Sweden', 'SE', 'sweden');
insert into country(country_name, country_code, country_slug) values ('Congo (Brazzaville)', 'CG', 'congo-brazzaville');
insert into country(country_name, country_code, country_slug) values ('Viet Nam', 'VN', 'vietnam');
insert into country(country_name, country_code, country_slug) values ('Seychelles', 'SC', 'seychelles');
insert into country(country_name, country_code, country_slug) values ('Jersey', 'JE', 'jersey');
insert into country(country_name, country_code, country_slug) values ('Spain', 'ES', 'spain');
insert into country(country_name, country_code, country_slug) values ('Swaziland', 'SZ', 'swaziland');
insert into country(country_name, country_code, country_slug) values ('US Minor Outlying Islands', 'UM', 'us-minor-outlying-islands');
insert into country(country_name, country_code, country_slug) values ('Cambodia', 'KH', 'cambodia');
insert into country(country_name, country_code, country_slug) values ('Cape Verde', 'CV', 'cape-verde');
insert into country(country_name, country_code, country_slug) values ('Colombia', 'CO', 'colombia');
insert into country(country_name, country_code, country_slug) values ('Dominica', 'DM', 'dominica');
insert into country(country_name, country_code, country_slug) values ('Guinea-Bissau', 'GW', 'guinea-bissau');
insert into country(country_name, country_code, country_slug) values ('Niger', 'NE', 'niger');
insert into country(country_name, country_code, country_slug) values ('Uganda', 'UG', 'uganda');
insert into country(country_name, country_code, country_slug) values ('Namibia', 'NA', 'namibia');
insert into country(country_name, country_code, country_slug) values ('Botswana', 'BW', 'botswana');
insert into country(country_name, country_code, country_slug) values ('Netherlands', 'NL', 'netherlands');
insert into country(country_name, country_code, country_slug) values ('Republic of Kosovo', 'XK', 'kosovo');
insert into country(country_name, country_code, country_slug) values ('Cyprus', 'CY', 'cyprus');
insert into country(country_name, country_code, country_slug) values ('Faroe Islands', 'FO', 'faroe-islands');
insert into country(country_name, country_code, country_slug) values ('Timor-Leste', 'TL', 'timor-leste');
insert into country(country_name, country_code, country_slug) values ('Turkey', 'TR', 'turkey');
insert into country(country_name, country_code, country_slug) values ('Cuba', 'CU', 'cuba');
insert into country(country_name, country_code, country_slug) values ('French Guiana', 'GF', 'french-guiana');
insert into country(country_name, country_code, country_slug) values ('Lithuania', 'LT', 'lithuania');
insert into country(country_name, country_code, country_slug) values ('Senegal', 'SN', 'senegal');
insert into country(country_name, country_code, country_slug) values ('Congo (Kinshasa)', 'CD', 'congo-kinshasa');
insert into country(country_name, country_code, country_slug) values ('Costa Rica', 'CR', 'costa-rica');
insert into country(country_name, country_code, country_slug) values ('Greece', 'GR', 'greece');
insert into country(country_name, country_code, country_slug) values ('Antarctica', 'AQ', 'antarctica');
insert into country(country_name, country_code, country_slug) values ('Central African Republic', 'CF', 'central-african-republic');
insert into country(country_name, country_code, country_slug) values ('Chile', 'CL', 'chile');
insert into country(country_name, country_code, country_slug) values ('Slovakia', 'SK', 'slovakia');
insert into country(country_name, country_code, country_slug) values ('Belize', 'BZ', 'belize');
insert into country(country_name, country_code, country_slug) values ('Holy See (Vatican City State)', 'VA', 'holy-see-vatican-city-state');
insert into country(country_name, country_code, country_slug) values ('Israel', 'IL', 'israel');
insert into country(country_name, country_code, country_slug) values ('Pakistan', 'PK', 'pakistan');
insert into country(country_name, country_code, country_slug) values ('Angola', 'AO', 'angola');
insert into country(country_name, country_code, country_slug) values ('Burundi', 'BI', 'burundi');
insert into country(country_name, country_code, country_slug) values ('Ethiopia', 'ET', 'ethiopia');
insert into country(country_name, country_code, country_slug) values ('Moldova', 'MD', 'moldova');
insert into country(country_name, country_code, country_slug) values ('Tokelau', 'TK', 'tokelau');
insert into country(country_name, country_code, country_slug) values ('Côte d''Ivoire', 'CI', 'cote-divoire');
insert into country(country_name, country_code, country_slug) values ('Gabon', 'GA', 'gabon');
insert into country(country_name, country_code, country_slug) values ('Belarus', 'BY', 'belarus');
insert into country(country_name, country_code, country_slug) values ('Guernsey', 'GG', 'guernsey');
insert into country(country_name, country_code, country_slug) values ('Sierra Leone', 'SL', 'sierra-leone');
insert into country(country_name, country_code, country_slug) values ('Western Sahara', 'EH', 'western-sahara');
insert into country(country_name, country_code, country_slug) values ('Tanzania, United Republic of', 'TZ', 'tanzania');
insert into country(country_name, country_code, country_slug) values ('French Polynesia', 'PF', 'french-polynesia');
insert into country(country_name, country_code, country_slug) values ('Palestinian Territory', 'PS', 'palestine');
insert into country(country_name, country_code, country_slug) values ('Qatar', 'QA', 'qatar');
insert into country(country_name, country_code, country_slug) values ('Samoa', 'WS', 'samoa');
insert into country(country_name, country_code, country_slug) values ('San Marino', 'SM', 'san-marino');
insert into country(country_name, country_code, country_slug) values ('Somalia', 'SO', 'somalia');
insert into country(country_name, country_code, country_slug) values ('British Virgin Islands', 'VG', 'british-virgin-islands');
insert into country(country_name, country_code, country_slug) values ('Cook Islands', 'CK', 'cook-islands');
insert into country(country_name, country_code, country_slug) values ('Estonia', 'EE', 'estonia');
insert into country(country_name, country_code, country_slug) values ('Madagascar', 'MG', 'madagascar');
insert into country(country_name, country_code, country_slug) values ('Switzerland', 'CH', 'switzerland');
insert into country(country_name, country_code, country_slug) values ('Turks and Caicos Islands', 'TC', 'turks-and-caicos-islands');
insert into country(country_name, country_code, country_slug) values ('British Indian Ocean Territory', 'IO', 'british-indian-ocean-territory');
insert into country(country_name, country_code, country_slug) values ('Gibraltar', 'GI', 'gibraltar');
insert into country(country_name, country_code, country_slug) values ('Singapore', 'SG', 'singapore');
insert into country(country_name, country_code, country_slug) values ('Algeria', 'DZ', 'algeria');
insert into country(country_name, country_code, country_slug) values ('Myanmar', 'MM', 'myanmar');
insert into country(country_name, country_code, country_slug) values ('Eritrea', 'ER', 'eritrea');
insert into country(country_name, country_code, country_slug) values ('Jamaica', 'JM', 'jamaica');
insert into country(country_name, country_code, country_slug) values ('Monaco', 'MC', 'monaco');
insert into country(country_name, country_code, country_slug) values ('Chad', 'TD', 'chad');
insert into country(country_name, country_code, country_slug) values ('Iran, Islamic Republic of', 'IR', 'iran');
insert into country(country_name, country_code, country_slug) values ('Saint-Barthélemy', 'BL', 'saint-barthélemy');
insert into country(country_name, country_code, country_slug) values ('Fiji', 'FJ', 'fiji');
insert into country(country_name, country_code, country_slug) values ('Mozambique', 'MZ', 'mozambique');
insert into country(country_name, country_code, country_slug) values ('Sudan', 'SD', 'sudan');
insert into country(country_name, country_code, country_slug) values ('Anguilla', 'AI', 'anguilla');
insert into country(country_name, country_code, country_slug) values ('Bahamas', 'BS', 'bahamas');
insert into country(country_name, country_code, country_slug) values ('ALA Aland Islands', 'AX', 'ala-aland-islands');
insert into country(country_name, country_code, country_slug) values ('French Southern Territories', 'TF', 'french-southern-territories');
insert into country(country_name, country_code, country_slug) values ('Montenegro', 'ME', 'montenegro');
insert into country(country_name, country_code, country_slug) values ('Venezuela (Bolivarian Republic)', 'VE', 'venezuela');
insert into country(country_name, country_code, country_slug) values ('Yemen', 'YE', 'yemen');
insert into country(country_name, country_code, country_slug) values ('Ecuador', 'EC', 'ecuador');
insert into country(country_name, country_code, country_slug) values ('Lao PDR', 'LA', 'lao-pdr');
insert into country(country_name, country_code, country_slug) values ('Latvia', 'LV', 'latvia');
insert into country(country_name, country_code, country_slug) values ('United Kingdom', 'GB', 'united-kingdom');
insert into country(country_name, country_code, country_slug) values ('Austria', 'AT', 'austria');
insert into country(country_name, country_code, country_slug) values ('Guatemala', 'GT', 'guatemala');
insert into country(country_name, country_code, country_slug) values ('Kyrgyzstan', 'KG', 'kyrgyzstan');
insert into country(country_name, country_code, country_slug) values ('Romania', 'RO', 'romania');
insert into country(country_name, country_code, country_slug) values ('Bhutan', 'BT', 'bhutan');
insert into country(country_name, country_code, country_slug) values ('Isle of Man', 'IM', 'isle-of-man');
insert into country(country_name, country_code, country_slug) values ('Lebanon', 'LB', 'lebanon');
insert into country(country_name, country_code, country_slug) values ('South Africa', 'ZA', 'south-africa');
insert into country(country_name, country_code, country_slug) values ('Armenia', 'AM', 'armenia');
insert into country(country_name, country_code, country_slug) values ('United States of America', 'US', 'united-states');
insert into country(country_name, country_code, country_slug) values ('Vanuatu', 'VU', 'vanuatu');
insert into country(country_name, country_code, country_slug) values ('Tuvalu', 'TV', 'tuvalu');
insert into country(country_name, country_code, country_slug) values ('Finland', 'FI', 'finland');
insert into country(country_name, country_code, country_slug) values ('Italy', 'IT', 'italy');
insert into country(country_name, country_code, country_slug) values ('Korea (South)', 'KR', 'korea-south');
insert into country(country_name, country_code, country_slug) values ('Taiwan, Republic of China', 'TW', 'taiwan');
insert into country(country_name, country_code, country_slug) values ('Afghanistan', 'AF', 'afghanistan');
insert into country(country_name, country_code, country_slug) values ('Sao Tome and Principe', 'ST', 'sao-tome-and-principe');
insert into country(country_name, country_code, country_slug) values ('Sri Lanka', 'LK', 'sri-lanka');
insert into country(country_name, country_code, country_slug) values ('Tajikistan', 'TJ', 'tajikistan');
insert into country(country_name, country_code, country_slug) values ('Thailand', 'TH', 'thailand');
insert into country(country_name, country_code, country_slug) values ('Albania', 'AL', 'albania');
insert into country(country_name, country_code, country_slug) values ('Guadeloupe', 'GP', 'guadeloupe');
insert into country(country_name, country_code, country_slug) values ('Kuwait', 'KW', 'kuwait');
insert into country(country_name, country_code, country_slug) values ('Saint-Martin (French part)', 'MF', 'saint-martin-french-part');
insert into country(country_name, country_code, country_slug) values ('Solomon Islands', 'SB', 'solomon-islands');
insert into country(country_name, country_code, country_slug) values ('Syrian Arab Republic (Syria)', 'SY', 'syria');
insert into country(country_name, country_code, country_slug) values ('Tunisia', 'TN', 'tunisia');
insert into country(country_name, country_code, country_slug) values ('Antigua and Barbuda', 'AG', 'antigua-and-barbuda');
insert into country(country_name, country_code, country_slug) values ('India', 'IN', 'india');
insert into country(country_name, country_code, country_slug) values ('Saint Pierre and Miquelon', 'PM', 'saint-pierre-and-miquelon');
insert into country(country_name, country_code, country_slug) values ('Canada', 'CA', 'canada');
insert into country(country_name, country_code, country_slug) values ('Honduras', 'HN', 'honduras');
insert into country(country_name, country_code, country_slug) values ('New Caledonia', 'NC', 'new-caledonia');
insert into country(country_name, country_code, country_slug) values ('Norfolk Island', 'NF', 'norfolk-island');
insert into country(country_name, country_code, country_slug) values ('Egypt', 'EG', 'egypt');
insert into country(country_name, country_code, country_slug) values ('Palau', 'PW', 'palau');
insert into country(country_name, country_code, country_slug) values ('Portugal', 'PT', 'portugal');
insert into country(country_name, country_code, country_slug) values ('Bahrain', 'BH', 'bahrain');
insert into country(country_name, country_code, country_slug) values ('Bouvet Island', 'BV', 'bouvet-island');
insert into country(country_name, country_code, country_slug) values ('Bulgaria', 'BG', 'bulgaria');
insert into country(country_name, country_code, country_slug) values ('Cocos (Keeling) Islands', 'CC', 'cocos-keeling-islands');
insert into country(country_name, country_code, country_slug) values ('Kiribati', 'KI', 'kiribati');
insert into country(country_name, country_code, country_slug) values ('Niue', 'NU', 'niue');
insert into country(country_name, country_code, country_slug) values ('Svalbard and Jan Mayen Islands', 'SJ', 'svalbard-and-jan-mayen-islands');
insert into country(country_name, country_code, country_slug) values ('Argentina', 'AR', 'argentina');
insert into country(country_name, country_code, country_slug) values ('Djibouti', 'DJ', 'djibouti');
insert into country(country_name, country_code, country_slug) values ('Heard and Mcdonald Islands', 'HM', 'heard-and-mcdonald-islands');
insert into country(country_name, country_code, country_slug) values ('Zimbabwe', 'ZW', 'zimbabwe');
insert into country(country_name, country_code, country_slug) values ('Australia', 'AU', 'australia');
insert into country(country_name, country_code, country_slug) values ('Martinique', 'MQ', 'martinique');
insert into country(country_name, country_code, country_slug) values ('Saudi Arabia', 'SA', 'saudi-arabia');
insert into country(country_name, country_code, country_slug) values ('Brazil', 'BR', 'brazil');
insert into country(country_name, country_code, country_slug) values ('Guyana', 'GY', 'guyana');
insert into country(country_name, country_code, country_slug) values ('Malaysia', 'MY', 'malaysia');
insert into country(country_name, country_code, country_slug) values ('Benin', 'BJ', 'benin');
insert into country(country_name, country_code, country_slug) values ('Falkland Islands (Malvinas)', 'FK', 'falkland-islands-malvinas');
insert into country(country_name, country_code, country_slug) values ('Malawi', 'MW', 'malawi');
insert into country(country_name, country_code, country_slug) values ('Oman', 'OM', 'oman');
insert into country(country_name, country_code, country_slug) values ('Cayman Islands', 'KY', 'cayman-islands');
insert into country(country_name, country_code, country_slug) values ('Croatia', 'HR', 'croatia');
insert into country(country_name, country_code, country_slug) values ('Kazakhstan', 'KZ', 'kazakhstan');
insert into country(country_name, country_code, country_slug) values ('Togo', 'TG', 'togo');
insert into country(country_name, country_code, country_slug) values ('Uruguay', 'UY', 'uruguay');
insert into country(country_name, country_code, country_slug) values ('Virgin Islands, US', 'VI', 'virgin-islands');
insert into country(country_name, country_code, country_slug) values ('Bosnia and Herzegovina', 'BA', 'bosnia-and-herzegovina');
insert into country(country_name, country_code, country_slug) values ('Ghana', 'GH', 'ghana');
insert into country(country_name, country_code, country_slug) values ('Marshall Islands', 'MH', 'marshall-islands');
insert into country(country_name, country_code, country_slug) values ('South Sudan', 'SS', 'south-sudan');
insert into country(country_name, country_code, country_slug) values ('Mongolia', 'MN', 'mongolia');
insert into country(country_name, country_code, country_slug) values ('Panama', 'PA', 'panama');
insert into country(country_name, country_code, country_slug) values ('Saint Lucia', 'LC', 'saint-lucia');
insert into country(country_name, country_code, country_slug) values ('South Georgia and the South Sandwich Islands', 'GS', 'south-georgia-and-the-south-sandwich-islands');
insert into country(country_name, country_code, country_slug) values ('Lesotho', 'LS', 'lesotho');
insert into country(country_name, country_code, country_slug) values ('Liberia', 'LR', 'liberia');
insert into country(country_name, country_code, country_slug) values ('Tonga', 'TO', 'tonga');
insert into country(country_name, country_code, country_slug) values ('United Arab Emirates', 'AE', 'united-arab-emirates');
insert into country(country_name, country_code, country_slug) values ('Nigeria', 'NG', 'nigeria');
insert into country(country_name, country_code, country_slug) values ('Pitcairn', 'PN', 'pitcairn');
insert into country(country_name, country_code, country_slug) values ('Wallis and Futuna Islands', 'WF', 'wallis-and-futuna-islands');
insert into country(country_name, country_code, country_slug) values ('Ireland', 'IE', 'ireland');
insert into country(country_name, country_code, country_slug) values ('Nauru', 'NR', 'nauru');
insert into country(country_name, country_code, country_slug) values ('Nepal', 'NP', 'nepal');
insert into country(country_name, country_code, country_slug) values ('Maldives', 'MV', 'maldives');
insert into country(country_name, country_code, country_slug) values ('Turkmenistan', 'TM', 'turkmenistan');
insert into country(country_name, country_code, country_slug) values ('Suriname', 'SR', 'suriname');
insert into country(country_name, country_code, country_slug) values ('Andorra', 'AD', 'andorra');
insert into country(country_name, country_code, country_slug) values ('El Salvador', 'SV', 'el-salvador');
insert into country(country_name, country_code, country_slug) values ('Indonesia', 'ID', 'indonesia');
insert into country(country_name, country_code, country_slug) values ('Poland', 'PL', 'poland');
insert into country(country_name, country_code, country_slug) values ('Netherlands Antilles', 'AN', 'netherlands-antilles');
insert into country(country_name, country_code, country_slug) values ('New Zealand', 'NZ', 'new-zealand');
insert into country(country_name, country_code, country_slug) values ('Saint Vincent and Grenadines', 'VC', 'saint-vincent-and-the-grenadines');
insert into country(country_name, country_code, country_slug) values ('Aruba', 'AW', 'aruba');
insert into country(country_name, country_code, country_slug) values ('Mauritius', 'MU', 'mauritius');
insert into country(country_name, country_code, country_slug) values ('Mexico', 'MX', 'mexico');
insert into country(country_name, country_code, country_slug) values ('Grenada', 'GD', 'grenada');
insert into country(country_name, country_code, country_slug) values ('Iraq', 'IQ', 'iraq');
insert into country(country_name, country_code, country_slug) values ('Norway', 'NO', 'norway');
insert into country(country_name, country_code, country_slug) values ('Paraguay', 'PY', 'paraguay');
insert into country(country_name, country_code, country_slug) values ('Bermuda', 'BM', 'bermuda');
insert into country(country_name, country_code, country_slug) values ('Dominican Republic', 'DO', 'dominican-republic');
insert into country(country_name, country_code, country_slug) values ('Saint Helena', 'SH', 'saint-helena');
insert into country(country_name, country_code, country_slug) values ('Belgium', 'BE', 'belgium');
insert into country(country_name, country_code, country_slug) values ('Peru', 'PE', 'peru');
insert into country(country_name, country_code, country_slug) values ('Philippines', 'PH', 'philippines');
insert into country(country_name, country_code, country_slug) values ('Liechtenstein', 'LI', 'liechtenstein');
insert into country(country_name, country_code, country_slug) values ('Malta', 'MT', 'malta');
insert into country(country_name, country_code, country_slug) values ('Northern Mariana Islands', 'MP', 'northern-mariana-islands');
insert into country(country_name, country_code, country_slug) values ('Saint Kitts and Nevis', 'KN', 'saint-kitts-and-nevis');
insert into country(country_name, country_code, country_slug) values ('Equatorial Guinea', 'GQ', 'equatorial-guinea');
insert into country(country_name, country_code, country_slug) values ('Hungary', 'HU', 'hungary');
insert into country(country_name, country_code, country_slug) values ('Macao, SAR China', 'MO', 'macao-sar-china');
insert into country(country_name, country_code, country_slug) values ('Nicaragua', 'NI', 'nicaragua');
insert into country(country_name, country_code, country_slug) values ('Gambia', 'GM', 'gambia');
insert into country(country_name, country_code, country_slug) values ('Guinea', 'GN', 'guinea');
insert into country(country_name, country_code, country_slug) values ('Luxembourg', 'LU', 'luxembourg');
insert into country(country_name, country_code, country_slug) values ('Ukraine', 'UA', 'ukraine');
insert into country(country_name, country_code, country_slug) values ('Barbados', 'BB', 'barbados');
insert into country(country_name, country_code, country_slug) values ('Christmas Island', 'CX', 'christmas-island');
insert into country(country_name, country_code, country_slug) values ('Uzbekistan', 'UZ', 'uzbekistan');
insert into country(country_name, country_code, country_slug) values ('Macedonia, Republic of', 'MK', 'macedonia');
insert into country(country_name, country_code, country_slug) values ('Czech Republic', 'CZ', 'czech-republic');
insert into country(country_name, country_code, country_slug) values ('Greenland', 'GL', 'greenland');
insert into country(country_name, country_code, country_slug) values ('Libya', 'LY', 'libya');
insert into country(country_name, country_code, country_slug) values ('Azerbaijan', 'AZ', 'azerbaijan');
insert into country(country_name, country_code, country_slug) values ('Mali', 'ML', 'mali');
insert into country(country_name, country_code, country_slug) values ('Mauritania', 'MR', 'mauritania');
insert into country(country_name, country_code, country_slug) values ('Russian Federation', 'RU', 'russia');
insert into country(country_name, country_code, country_slug) values ('Hong Kong, SAR China', 'HK', 'hong-kong-sar-china');
insert into country(country_name, country_code, country_slug) values ('Korea (North)', 'KP', 'korea-north');
insert into country(country_name, country_code, country_slug) values ('Puerto Rico', 'PR', 'puerto-rico');
insert into country(country_name, country_code, country_slug) values ('Serbia', 'RS', 'serbia');
insert into country(country_name, country_code, country_slug) values ('Denmark', 'DK', 'denmark');
insert into country(country_name, country_code, country_slug) values ('Iceland', 'IS', 'iceland');
insert into country(country_name, country_code, country_slug) values ('Papua New Guinea', 'PG', 'papua-new-guinea');
insert into country(country_name, country_code, country_slug) values ('Burkina Faso', 'BF', 'burkina-faso');
